version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    target-branch: development
    reviewers:
      - echarrod
      - klaidas
      - LKDraytonBrown
    assignees:
      - echarrod
